name: Bug Report
description: File a bug report.
title: "<insert bug issue title here>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please help us out by providing as much information as you can.
  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        What version of Mir are you running? (hint: you can launch Mir inside an existing session with the `--version` flag)
      default: latest stable
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        What environment are you running Mir in? Please mention your hardware specifications, OS, Mesa (or nvidia driver) version.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
        (hint: You can run your compositor with `<compositor launch command> 2&>1 | tee <log_file_name>` if you're having issues capturing logs)
      render: shell
