name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-summary
    attributes:
      label: Summary
      description: An overview of the feature.
      placeholder: Tell us what you want!
      value: "I would like Mir to do this cool thing."
    validations:
      required: true
  - type: textarea
    id: feature-details
    attributes:
      label: Details
      description: More details about how the feature should behave, how the user would interact with it, and its interactions with other parts of Mir.
      placeholder: Tell us more.
      value: "The feature should be enabled through.... If feature Foo is enabled, they should interact in this way: ..."
    validations:
      required: optional
